[package]
name = "juixe-bot"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
serenity = { version = "0.11.5", default_features = false, features = ["client", "gateway", "rustls_backend", "model"]}
dotenv = "0.15.0"
tokio = { version = "1.23.0", features = ["macros", "rt"] }

